# Generated by Django 4.2.2 on 2023-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_downloader', '0002_dbdownload_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdownload',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dbdownload',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
